### ISSUE TITLE
Using $ in variable name breaks plugin v

### ISSUE THREAD

**Issue by jsenk** [cschuller/yakjs#47]
![plugin-function](https://cloud.githubusercontent.com/assets/1361759/12677879/db3be4b0-c669-11e5-97d6-37f651e8d42e.PNG)

When extracting the plugin function during uploading a new plugin, if the current file makes use of a variable with the $ character, the regex will stop matching on that character. This appears to be because the regex will greedily match until it reaches the $ based on the regex string. 

This could be fixed by instead matching until it hits null. 

`        var matchedGroups = yak.global.regexGroup(content, 'function ([A-Z][A-Za-z]*)[^\0]*');
`

**Comment by cschuller** [comment]
Thanks for your feedback. I will add the change to the upcoming YAKjs 2.0
