### ISSUE TITLE
YAKja crashed on connection closed event

### ISSUE THREAD

**Issue by rlukacik** [cschuller/yakjs#52]
YAKjs is crashed when the client is send on unload event message via websocket and then close the websocket connection. See attachment for the error. Temporarily fixed Receiver.js, added check to this.status is undefined. Looks like Receiver.prototype.cleanup function is called before. Maybe update of this npm package will solve the problem.
![yakconnectionclosederror](https://cloud.githubusercontent.com/assets/16306734/14540069/91ada6e8-0283-11e6-8554-5a07c67a827d.PNG)

**Comment by cschuller** [comment]
Will be fixed with YAKjs 3.0

**Comment by cschuller** [comment]
Hello Ricard,

Check out the new YAKjs version 3.0.3 - this problem should be solved using a newer version of the WebSocket server.

**Comment by rlukacik** [comment]
Thanks Christian, I will check it.
BR,
Richard
